package info.anodsplace.carwidget.iconpack

import androidx.annotation.DrawableRes

data class IconDescription(
    val labelRes: Int,
    @param:DrawableRes val iconRes: Int,
    @param:DrawableRes val folderIconRes: Int
)

val IconDescriptions: List<IconDescription> = listOf(
    IconDescription(R.string.icon_category_travel, R.drawable.baseline_flight_24, R.drawable.folder_flight_24),
    IconDescription(R.string.icon_category_audio, R.drawable.baseline_music_note_24, R.drawable.folder_music_note_24),
    IconDescription(R.string.icon_category_books, R.drawable.baseline_menu_book_24, R.drawable.folder_menu_book_24),
    IconDescription(R.string.icon_category_authenticator, R.drawable.baseline_verified_user_24, R.drawable.folder_verified_user_24),
    IconDescription(R.string.icon_category_cars, R.drawable.baseline_directions_car_24, R.drawable.folder_directions_car_24),
    IconDescription(R.string.icon_category_camera, R.drawable.baseline_photo_camera_24, R.drawable.folder_photo_camera_24),
    IconDescription(R.string.icon_category_children, R.drawable.baseline_child_care_24, R.drawable.folder_child_care_24),
    IconDescription(R.string.icon_category_sleep, R.drawable.baseline_bedtime_24, R.drawable.folder_bedtime_24),
    IconDescription(R.string.icon_category_cloud_storage, R.drawable.baseline_cloud_24, R.drawable.folder_cloud_24),
    IconDescription(R.string.icon_category_contacts, R.drawable.baseline_contacts_24, R.drawable.folder_contacts_24),
    IconDescription(R.string.icon_category_comics, R.drawable.baseline_auto_stories_24, R.drawable.folder_auto_stories_24),
    IconDescription(R.string.icon_category_crypto, R.drawable.baseline_monetization_on_24, R.drawable.folder_monetization_on_24),
    IconDescription(R.string.icon_category_dating, R.drawable.baseline_favorite_24, R.drawable.folder_favorite_24),
    IconDescription(R.string.icon_category_download, R.drawable.baseline_file_download_24, R.drawable.folder_file_download_24),
    IconDescription(R.string.icon_category_education, R.drawable.baseline_school_24, R.drawable.folder_school_24),
    IconDescription(R.string.icon_category_email, R.drawable.baseline_email_24, R.drawable.folder_email_24),
    IconDescription(R.string.icon_category_files, R.drawable.baseline_folder_24, R.drawable.baseline_folder_24),
    IconDescription(R.string.icon_category_finance, R.drawable.baseline_account_balance_24, R.drawable.folder_account_balance_24),
    IconDescription(R.string.icon_category_fitness, R.drawable.baseline_fitness_center_24, R.drawable.folder_fitness_center_24),
    IconDescription(R.string.icon_category_food, R.drawable.baseline_fastfood_24, R.drawable.folder_fastfood_24),
    IconDescription(R.string.icon_category_health, R.drawable.baseline_health_and_safety_24, R.drawable.folder_health_and_safety_24),
    IconDescription(R.string.icon_category_home, R.drawable.baseline_home_24, R.drawable.folder_home_24),
    IconDescription(R.string.icon_category_humor, R.drawable.baseline_emoji_emotions_24, R.drawable.folder_emoji_emotions_24),
    IconDescription(R.string.icon_category_image, R.drawable.baseline_image_24, R.drawable.folder_image_24),
    IconDescription(R.string.icon_category_jobs, R.drawable.baseline_work_24, R.drawable.folder_work_24),
    IconDescription(R.string.icon_category_language_education, R.drawable.baseline_translate_24, R.drawable.folder_translate_24),
    IconDescription(R.string.icon_category_maps, R.drawable.baseline_map_24, R.drawable.folder_map_24),
    IconDescription(R.string.icon_category_movies, R.drawable.baseline_movie_24, R.drawable.folder_movie_24),
    IconDescription(R.string.icon_category_network_connection, R.drawable.baseline_wifi_24, R.drawable.folder_wifi_24),
    IconDescription(R.string.icon_category_news, R.drawable.baseline_article_24, R.drawable.folder_article_24),
    IconDescription(R.string.icon_category_office, R.drawable.baseline_apartment_24, R.drawable.folder_apartment_24),
    IconDescription(R.string.icon_category_painting, R.drawable.baseline_color_lens_24, R.drawable.folder_color_lens_24),
    IconDescription(R.string.icon_category_password_manager, R.drawable.baseline_lock_24, R.drawable.folder_lock_24),
    IconDescription(R.string.icon_category_personal_assistant, R.drawable.baseline_support_agent_24, R.drawable.folder_support_agent_24),
    IconDescription(R.string.icon_category_privacy_security, R.drawable.baseline_security_24, R.drawable.folder_security_24),
    IconDescription(R.string.icon_category_programming, R.drawable.baseline_code_24, R.drawable.folder_code_24),
    IconDescription(R.string.icon_category_public_transport, R.drawable.baseline_directions_bus_24, R.drawable.folder_directions_bus_24),
    IconDescription(R.string.icon_category_radio, R.drawable.baseline_radio_24, R.drawable.folder_radio_24),
    IconDescription(R.string.icon_category_religious_text, R.drawable.baseline_menu_book_24, R.drawable.folder_menu_book_24),
    IconDescription(R.string.icon_category_remote_control, R.drawable.baseline_settings_remote_24, R.drawable.folder_settings_remote_24),
    IconDescription(R.string.icon_category_scanner, R.drawable.baseline_document_scanner_24, R.drawable.folder_document_scanner_24),
    IconDescription(R.string.icon_category_settings, R.drawable.baseline_settings_24, R.drawable.folder_settings_24),
    IconDescription(R.string.icon_category_shopping, R.drawable.baseline_shopping_cart_24, R.drawable.folder_shopping_cart_24),
    IconDescription(R.string.icon_category_social_media, R.drawable.baseline_people_24, R.drawable.folder_people_24),
    IconDescription(R.string.icon_category_sport, R.drawable.baseline_sports_soccer_24, R.drawable.folder_sports_soccer_24),
    IconDescription(R.string.icon_category_stickers, R.drawable.baseline_collections_24, R.drawable.folder_collections_24),
    IconDescription(R.string.icon_category_taxi, R.drawable.baseline_local_taxi_24, R.drawable.folder_local_taxi_24),
    IconDescription(R.string.icon_category_text_messaging, R.drawable.baseline_message_24, R.drawable.folder_message_24),
    IconDescription(R.string.icon_category_theme, R.drawable.baseline_palette_24, R.drawable.folder_palette_24),
    IconDescription(R.string.icon_category_tips, R.drawable.baseline_tips_and_updates_24, R.drawable.folder_tips_and_updates_24),
    IconDescription(R.string.icon_category_todo_list, R.drawable.baseline_list_alt_24, R.drawable.folder_list_alt_24),
    IconDescription(R.string.icon_category_tools, R.drawable.baseline_build_24, R.drawable.folder_build_24),
    IconDescription(R.string.icon_category_trading, R.drawable.baseline_show_chart_24, R.drawable.folder_show_chart_24),
    IconDescription(R.string.icon_category_virtual_reality, R.drawable.baseline_view_in_ar_24, R.drawable.folder_view_in_ar_24),
    IconDescription(R.string.icon_category_vpn, R.drawable.baseline_vpn_key_24, R.drawable.folder_vpn_key_24),
    IconDescription(R.string.icon_category_watch, R.drawable.baseline_watch_later_24, R.drawable.folder_watch_later_24),
    IconDescription(R.string.icon_category_weather, R.drawable.baseline_wb_sunny_24, R.drawable.folder_wb_sunny_24),
    IconDescription(R.string.icon_category_web_browser, R.drawable.baseline_public_24, R.drawable.folder_public_24),
)
